In [1]:
# Import libraries for machine learning, pandas, and numpy
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression




In [2]:
# Load data from final_merged_table.csv
df = pd.read_csv('final_merged_table copy.csv')

/var/folders/7t/kx7mpsk15210p47h__d0lpt80000gn/T/ipykernel_30482/795297802.py:2: DtypeWarning: Columns (13,20,23,27,28,39,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('final_merged_table copy.csv')


In [3]:
# list columns 
df.columns

Index(['Unnamed: 0.5', 'Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2',
       'Unnamed: 0.1', 'Unnamed: 0', 'driverId', 'dob', 'nationality',
       'dob_formatted', 'raceId', 'grid', 'results_position', 'positionText',
       'positionOrder', 'results_points', 'results_laps', 'fastestLap', 'rank',
       'race_ms', 'results_fastestlaptime', 'fastestLapSpeed', 'statusId',
       'status', 'year', 'round', 'circuitId', 'races_name', 'date',
       'dstnd_points', 'dstnd_position', 'wins', 'lapt_lap', 'lapt_position',
       'lap_ms', 'pit_lap', 'pit_ms', 'quali_position', 'sprslt_grid',
       'sprslt_position', 'sprslt_points', 'sprslt_quali_ms',
       'sprslt_fastestLap', 'race_lat', 'race_lng', 'nationality_lat',
       'nationality_lat.1', 'nationality_lat.2', 'nationality_lat.3',
       'driver_country', 'country_lat', 'country_lng'],
      dtype='object')

In [4]:
# list all driver ids in driver id column
df['driverId'].unique()

array([  1,   4,   8, 815, 830, 832, 839,  20, 846, 852, 853, 854, 825,
       840, 842, 844, 847, 848, 849, 822, 855, 817, 841,   9, 251, 106,
       681, 285, 120, 264, 802, 664, 601, 647, 497, 452, 496, 455, 630,
       209, 665, 276, 606, 577, 850, 801, 599, 550, 856, 807, 756, 151,
       384, 253, 700, 399, 119, 270, 437, 620, 518, 549, 268, 310, 214,
       397, 836, 101, 339, 486, 330,  82,  25, 359,  26, 213, 137, 745,
       265, 405, 379, 292, 168, 136, 218, 196, 373, 238,  27, 230, 785,
       414, 765, 667, 449, 786, 149, 733,  93, 307, 382, 335, 706, 838,
       555, 541, 805, 554, 191, 774, 833, 714, 295,  11, 228, 135, 523,
       252,  39, 537, 834, 526, 508, 489, 559, 662, 131, 178, 471, 255,
       357, 241, 812, 465,  17, 325, 563, 142,  66, 827, 479, 640, 160,
        89, 504, 284,  33, 512, 633, 816, 779, 442,  57, 109, 239,  31,
       288, 738, 524, 644,  34, 505, 763,  12, 296, 686, 282,  10, 428,
       321, 324, 684,  18, 614, 146, 139, 752, 143, 594, 424,  9

In [5]:
# count of wins for driverID 11
df[df['driverId'] == 11]['wins'].sum()

0.0

In [6]:
df['year'].unique()

array([2021., 2022.,   nan])

In [7]:
df[df['driverId']==1]['wins'].count()

759

In [8]:
df[df['driverId']==4]['wins'].sum()

0.0

In [9]:
# List race names
df['races_name'].unique()

array(['São Paulo Grand Prix', 'Austrian Grand Prix',
       'Brazilian Grand Prix', 'British Grand Prix', 'Italian Grand Prix',
       'Emilia Romagna Grand Prix', nan], dtype=object)

In [10]:
# count of results laps from driver id 10
df[df['driverId']==10]['results_laps'].count()

0

In [11]:
df[df['driverId']==10]['results_laps'].sum()

0.0

In [12]:
#Show all dates in date column in descending order
df['date'].sort_values(ascending=False)


16056    2022-11-13
4283     2022-11-13
4353     2022-11-13
4352     2022-11-13
4351     2022-11-13
            ...    
16883           NaN
16884           NaN
16885           NaN
16886           NaN
16887           NaN
Name: date, Length: 16888, dtype: object

In [13]:
df['quali_position'].unique()

array([ 1., 10., 14.,  4.,  2.,  6., 11., 12.,  8., 13., 20., 19.,  3.,
        5., 17., 15.,  7.,  9., 18., 16., nan])

In [14]:
df.head()

Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0             0             0             0             0             0   
1             1             1             1             1             1   
2             2             2             2             2             2   
3             3             3             3             3             3   
4             4             4             4             4             4   

   Unnamed: 0  driverId       dob nationality dob_formatted  ...  \
0           0         1  1/7/1985     British          1985  ...   
1           1         1  1/7/1985     British          1985  ...   
2           2         1  1/7/1985     British          1985  ...   
3           3         1  1/7/1985     British          1985  ...   
4           4         1  1/7/1985     British          1985  ...   

   sprslt_fastestLap  race_lat  race_lng nationality_lat  nationality_lat.1  \
0                5.0   -23.702   -46.698          52.078             52.078   
1                5.0   -23.702   -46.698          52.078             52.078   
2                5.0   -23.702   -46.698          52.078             52.078   
3                5.0   -23.702   -46.698          52.078             52.078   
4                5.0   -23.702   -46.698          52.078             52.078   

   nationality_lat.2  nationality_lat.3  driver_country  country_lat  \
0             52.078             52.078  United Kingdom          NaN   
1             52.078             52.078  United Kingdom          NaN   
2             52.078             52.078  United Kingdom          NaN   
3             52.078             52.078  United Kingdom          NaN   
4             52.078             52.078  United Kingdom          NaN   

   country_lng  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 52 columns]

In [15]:
# Show all driver id's that have a qualifications position of 1 or more
df[df['quali_position'] >= 1]['driverId'].unique()

array([  1,   4,   8, 815, 830, 832, 839,  20, 846, 852, 853, 854, 825,
       840, 842, 844, 847, 848, 849, 822, 855, 817, 841,   9])

In [16]:
# drop race long column at the end of the table
df.drop(df.columns[[len(df.columns)-1]], axis=1, inplace=True)
df

Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0                 0             0             0             0             0   
1                 1             1             1             1             1   
2                 2             2             2             2             2   
3                 3             3             3             3             3   
4                 4             4             4             4             4   
...             ...           ...           ...           ...           ...   
16883         16883         16883         16883         16883         16883   
16884         16884         16884         16884         16884         16884   
16885         16885         16885         16885         16885         16885   
16886         16886         16886         16886         16886         16886   
16887         16887         16887         16887         16887         16887   

       Unnamed: 0  driverId        dob nationality dob_formatted  ...  \
0               0         1   1/7/1985     British          1985  ...   
1               1         1   1/7/1985     British          1985  ...   
2               2         1   1/7/1985     British          1985  ...   
3               3         1   1/7/1985     British          1985  ...   
4               4         1   1/7/1985     British          1985  ...   
...           ...       ...        ...         ...           ...  ...   
16883       16883       616  7/15/1928    American          1928  ...   
16884       16884       615  8/21/1913    American          1913  ...   
16885       16885       144  6/13/1966    Japanese          1966  ...   
16886       16886         7  2/28/1979      French          1979  ...   
16887       16887       453  11/1/1936     British          1936  ...   

       sprslt_quali_ms  sprslt_fastestLap  race_lat race_lng  nationality_lat  \
0              1770431                5.0   -23.702  -46.698          52.0780   
1              1770431                5.0   -23.702  -46.698          52.0780   
2              1770431                5.0   -23.702  -46.698          52.0780   
3              1770431                5.0   -23.702  -46.698          52.0780   
4              1770431                5.0   -23.702  -46.698          52.0780   
...                ...                ...       ...      ...              ...   
16883              NaN                NaN       NaN      NaN              NaN   
16884              NaN                NaN       NaN      NaN              NaN   
16885              NaN                NaN       NaN      NaN          35.6762   
16886              NaN                NaN       NaN      NaN          48.8566   
16887              NaN                NaN       NaN      NaN          52.0780   

       nationality_lat.1  nationality_lat.2  nationality_lat.3  \
0                52.0780            52.0780            52.0780   
1                52.0780            52.0780            52.0780   
2                52.0780            52.0780            52.0780   
3                52.0780            52.0780            52.0780   
4                52.0780            52.0780            52.0780   
...                  ...                ...                ...   
16883                NaN                NaN                NaN   
16884                NaN                NaN                NaN   
16885            35.6762            35.6762            35.6762   
16886            48.8566            48.8566            48.8566   
16887            52.0780            52.0780            52.0780   

       driver_country  country_lat  
0      United Kingdom          NaN  
1      United Kingdom          NaN  
2      United Kingdom          NaN  
3      United Kingdom          NaN  
4      United Kingdom          NaN  
...               ...          ...  
16883   United States          NaN  
16884   United States          NaN  
16885           Japan          NaN  
16886             NaN          NaN  
16887  U

In [17]:
df['races_name'].unique()

array(['São Paulo Grand Prix', 'Austrian Grand Prix',
       'Brazilian Grand Prix', 'British Grand Prix', 'Italian Grand Prix',
       'Emilia Romagna Grand Prix', nan], dtype=object)

In [18]:
# Add races lat and lng values
# Create a dictionary with race names as keys and lat,lng tuples as values
for i, row in df.iterrows():
    if df.at[i, 'races_name'] == 'São Paulo Grand Prix':
        df.at[i, 'race_lat'] = -23.702
        df.at[i, 'race_lng'] = -46.6980
    elif df.at[i, 'races_name'] == 'Austrian Grand Prix':
        df.at[i, 'race_lat'] = 47.219
        df.at[i, 'race_lng'] = 14.764
    elif df.at[i, 'races_name'] == 'Brazilian Grand Prix':
        df.at[i, 'race_lat'] = -23.702
        df.at[i, 'race_lng'] = -46.6980
    elif df.at[i, 'races_name'] == 'British Grand Prix':
        df.at[i, 'race_lat'] = 52.078
        df.at[i, 'race_lng'] = -1.016
    elif df.at[i, 'races_name'] == 'Italian Grand Prix':
        df.at[i, 'race_lat'] = 45.6200
        df.at[i, 'race_lng'] = 9.2900
    elif df.at[i, 'races_name'] == 'Emilia Romagna Grand Prix':
        df.at[i, 'race_lat'] = 44.3400
        df.at[i, 'race_lng'] = 11.6200
    else:
        # update columns for all other races
        df.at[i, 'race_lat'] = None
        df.at[i, 'race_lng'] = None

df

Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0                 0             0             0             0             0   
1                 1             1             1             1             1   
2                 2             2             2             2             2   
3                 3             3             3             3             3   
4                 4             4             4             4             4   
...             ...           ...           ...           ...           ...   
16883         16883         16883         16883         16883         16883   
16884         16884         16884         16884         16884         16884   
16885         16885         16885         16885         16885         16885   
16886         16886         16886         16886         16886         16886   
16887         16887         16887         16887         16887         16887   

       Unnamed: 0  driverId        dob nationality dob_formatted  ...  \
0               0         1   1/7/1985     British          1985  ...   
1               1         1   1/7/1985     British          1985  ...   
2               2         1   1/7/1985     British          1985  ...   
3               3         1   1/7/1985     British          1985  ...   
4               4         1   1/7/1985     British          1985  ...   
...           ...       ...        ...         ...           ...  ...   
16883       16883       616  7/15/1928    American          1928  ...   
16884       16884       615  8/21/1913    American          1913  ...   
16885       16885       144  6/13/1966    Japanese          1966  ...   
16886       16886         7  2/28/1979      French          1979  ...   
16887       16887       453  11/1/1936     British          1936  ...   

       sprslt_quali_ms  sprslt_fastestLap  race_lat race_lng  nationality_lat  \
0              1770431                5.0   -23.702  -46.698          52.0780   
1              1770431                5.0   -23.702  -46.698          52.0780   
2              1770431                5.0   -23.702  -46.698          52.0780   
3              1770431                5.0   -23.702  -46.698          52.0780   
4              1770431                5.0   -23.702  -46.698          52.0780   
...                ...                ...       ...      ...              ...   
16883              NaN                NaN       NaN      NaN              NaN   
16884              NaN                NaN       NaN      NaN              NaN   
16885              NaN                NaN       NaN      NaN          35.6762   
16886              NaN                NaN       NaN      NaN          48.8566   
16887              NaN                NaN       NaN      NaN          52.0780   

       nationality_lat.1  nationality_lat.2  nationality_lat.3  \
0                52.0780            52.0780            52.0780   
1                52.0780            52.0780            52.0780   
2                52.0780            52.0780            52.0780   
3                52.0780            52.0780            52.0780   
4                52.0780            52.0780            52.0780   
...                  ...                ...                ...   
16883                NaN                NaN                NaN   
16884                NaN                NaN                NaN   
16885            35.6762            35.6762            35.6762   
16886            48.8566            48.8566            48.8566   
16887            52.0780            52.0780            52.0780   

       driver_country  country_lat  
0      United Kingdom          NaN  
1      United Kingdom          NaN  
2      United Kingdom          NaN  
3      United Kingdom          NaN  
4      United Kingdom          NaN  
...               ...          ...  
16883   United States          NaN  
16884   United States          NaN  
16885           Japan          NaN  
16886             NaN          NaN  
16887  U

In [19]:
#list all values in race_lat column
df['race_lat'].unique()

array([-23.702,  47.219,  52.078,  45.62 ,  44.34 ,     nan])

In [20]:
df['nationality'].unique()

array(['British', 'Spanish', 'Finnish', 'Mexican', 'Dutch', 'French',
       'German', 'Japanese', 'Russian', 'Danish', 'Canadian',
       'Monegasque', 'Thai', 'Chinese', 'Australian', 'Italian', 'Polish',
       'South African', 'Belgian', 'Austrian', 'Argentine', 'American',
       'Brazilian', 'Colombian', 'Swedish', 'Rhodesian', 'New Zealander',
       'Indian', 'Portuguese', 'Swiss', 'Hungarian', 'Venezuela',
       'Uruguayan', 'Indonesian', 'Irish', 'Liechtenstein', 'Malaysian',
       'East German', 'Chilean', 'Argentine-Italian', 'Czech',
       'American-Italian'], dtype=object)

In [21]:
# Make a new column called country based on data from nationality - ['British', 'Spanish', 'Finnish', 'Mexican', 'Dutch', 'French','German', 'Japanese', 'Russian', 'Danish', 'Canadian','Monegasque', 'Thai', 'Chinese', 'Australian', 'Italian', 'Polish','South African', 'Belgian', 'Austrian', 'Argentine', 'American','Brazilian', 'Colombian', 'Swedish', 'Rhodesian', 'New Zealander','Indian', 'Portuguese', 'Swiss', 'Hungarian', 'Venezuelan','Uruguayan', 'Indonesian', 'Irish', 'Liechtensteiner', 'Malaysian','East German', 'Chilean', 'Argentine-Italian', 'Czech', 'American-Italian']
df['driver_country'] = None
for i, row in df.iterrows():
    if df.at[i, 'nationality'] == 'British':
        df.at[i, 'driver_country'] = 'United Kingdom'
    elif df.at[i, 'nationality'] == 'American':
        df.at[i, 'driver_country'] = 'United States'
    elif df.at[i,'nationality'] == 'Australian':
        df.at[i, 'driver_country'] = 'Australia'
    elif df.at[i, 'nationality'] == 'Finnish':
        df.at[i, 'driver_country'] = 'Finland'
    elif df.at[i, 'nationality'] == 'Mexican':
        df.at[i, 'driver_country'] = 'Mexico'
    elif df.at[i, 'nationality'] == 'Dutch':
        df.at[i, 'driver_country'] = 'Netherlands'
    elif df.at[i, 'nationality'] == 'German':
        df.at[i, 'driver_country'] = 'Germany'
    elif df.at[i, 'nationality'] == 'Japanese':
        df.at[i, 'driver_country'] = 'Japan'
    elif df.at[i, 'nationality'] == 'Russian':
        df.at[i, 'driver_country'] = 'Russia'
    elif df. at[i, 'nationality'] == 'Danish':
        df.at[i, 'driver_country'] = 'Denmark'
    elif df.at[i, 'nationality'] == 'Canadian':
        df.at[i, 'driver_country'] = 'Canada'
    elif df.at[i, 'nationality'] == 'Monegasque':
        df.at[i, 'driver_country'] = 'Monaco'
    elif df.at[i, 'nationality'] == 'Thai':
        df.at[i, 'driver_country'] = 'Thailand'
    elif df.at[i, 'nationality'] == 'Chinese':
        df.at[i, 'driver_country'] = 'China'
    elif df.at[i, 'nationality'] == 'Italian':
        df.at[i, 'driver_country'] = 'Italy'
    elif df.at[i, 'nationality'] == 'Polish':
        df.at[i, 'driver_country'] = 'Poland'
    elif df.at[i, 'nationality'] == 'South African':
        df.at[i, 'driver_country'] = 'South Africa'
    elif df.at[i, 'nationality'] == 'Belgian':
        df.at[i, 'driver_country'] = 'Belgium'
    elif df.at[i, 'nationality'] == 'Austrian':
        df.at[i, 'driver_country'] = 'Austria'
    elif df.at[i, 'nationality'] == 'Argentine':
        df.at[i, 'driver_country'] = 'Argentina'
    elif df.at[i, 'nationality'] == 'Brazilian':
        df.at[i, 'driver_country'] = 'Brazil'
    elif df.at[i, 'nationality'] == 'Colombian':
        df.at[i, 'driver_country'] = 'Colombia'
    elif df.at[i, 'nationality'] == 'Swedish':
        df.at[i, 'driver_country'] = 'Sweden'
    elif df.at[i, 'nationality'] == 'Rhodesian':
        df.at[i, 'driver_country'] = 'Zimbabwe'
    elif df.at[i, 'nationality'] == 'New Zealander':
        df.at[i, 'driver_country'] = 'New Zealand'
    elif df.at[i, 'nationality'] == 'Indian':
        df.at[i, 'driver_country'] = 'India'
    elif df.at[i, 'nationality'] == 'Portuguese':
        df.at[i, 'driver_country'] = 'Portugal'
    elif df.at[i, 'nationality'] == 'Swiss':
        df.at[i, 'driver_country'] = 'Switzerland'
    elif df.at[i, 'nationality'] == 'Hungarian':
        df.at[i, 'driver_country'] = 'Hungary'
    elif df.at[i, 'nationality'] == 'Venezuelan':
        df.at[i, 'nationality'] = 'Venezuela'
    elif df.at[i, 'nationality'] == 'Uruguayan':
        df.at[i, 'driver_country'] = 'Uruguay'
    elif df.at[i, 'nationality'] == 'Indonesian':
        df.at[i, 'driver_country'] = 'Indonesia'
    elif df.at[i, 'nationality'] == 'Irish':
        df.at[i, 'driver_country'] = 'Ireland'
    elif df.at[i, 'nationality'] ==  'Liechtensteiner':
        df.at[i, 'nationality'] = 'Liechtenstein'
    elif df.at[i, 'nationality'] == 'Malaysian':
        df.at[i, 'driver_country'] = 'Malaysia'
    elif df.at[i, 'nationality'] == 'East German':
        df.at[i, 'driver_country'] = 'Germany'
    elif df.at[i, 'nationality'] == 'Chilean':
        df.at[i, 'driver_country'] = 'Chile'
    elif df.at[i, 'nationality'] == 'Argentine-Italian':
        df.at[i, 'driver_country'] = 'Argentina'
    elif df.at[i, 'nationality'] == 'Czech':
        df.at[i, 'driver_country'] = 'Czech Republic'
    elif df.at[i, 'nationality'] == 'American-Italian':
        df.at[i, 'driver_country'] = 'United States'
    elif df.at[i, 'nationality'] == 'Spanish':
        df.at[i, 'driver_country'] = 'Spain'
    

In [22]:
# Create a country_lat and a country_lng column
# Create a country_lat and a country_lng column
df['country_lat'] = None
df['country_lng'] = None


# Loop through all rows and update country_lat and country_lng columns based on nationality
for i, row in df.iterrows():
    if df.at[i, 'driver_country'] == 'United Kingdom':
        df.at[i, 'country_lat'] == 51.5074
        df.at[i, 'country_lng'] == 0.1278
    elif df.at[i, 'driver_country'] == 'Spain':
        df.at[i, 'country_lat'] == 40.4168
        df.at[i, 'country_lng'] == -3.7038
    elif df.at[i, 'driver_country'] == 'Finland':
        df.at[i, 'country_lat'] == 60.1699
        df.at[i, 'country_lng'] == 24.9384
    elif df.at[i, 'driver_country'] == 'Mexico':
        df.at[i, 'country_lat'] == 19.4326
        df.at[i, 'country_lng'] == -99.1332
    elif df.at[i, 'driver_country'] == 'Netherlands':
        df.at[i, 'country_lat'] == 52.1326
        df.at[i, 'country_lng'] == 5.2913
    elif df.at[i, 'driver_country'] == 'France':
        df.at[i, 'country_lat'] == 48.8566
        df.at[i, 'country_lng'] == 2.3522
    elif df.at[i, 'driver_country'] == 'Germany':
        df.at[i, 'country_lat'] == 52.5200
        df.at[i, 'country_lng'] == 13.4050
    elif df.at[i, 'driver_country'] == 'Japan':
        df.at[i, 'country_lat'] == 35.6762
        df.at[i, 'country_lng'] == 139.6503
    elif df.at[i, 'driver_country'] == 'Netherlands':
        df.at[i, 'country_lat'] == 52.1326
        df.at[i, 'country_lng'] == 5.2913
    elif df.at[i, 'driver_country'] == 'Canada':
        df.at[i, 'country_lat'] == 43.6532
        df.at[i, 'country_lng'] == -79.3832
    elif df.at[i, 'driver_country'] == 'Monaco':
        df.at[i, 'country_lat'] == 43.7384
        df.at[i, 'country_lng'] == 7.4246
    elif df.at[i, 'driver_country'] == 'Thailand':
        df.at[i, 'country_lat'] == 13.7563
        df.at[i, 'country_lng'] == 100.5018
    elif df.at[i, 'driver_country'] == 'China':
        df.at[i, 'country_lat'] == 39.9042
        df.at[i, 'country_lng'] == 116.4074
    elif df.at[i, 'driver_country'] == 'Australia':
        df.at[i, 'country_lat'] == -33.8688
        df.at[i, 'country_lng'] == 151.2093
    elif df.at[i, 'driver_country'] == 'Italia':
        df.at[i, 'country_lat'] == 41.9028
        df.at[i, 'country_lng'] == 12.4964
    elif df.at[i, 'driver_country'] == 'Poland':
        df.at[i, 'country_lat'] == 52.2297
        df.at[i, 'country_lng'] == 21.0122
    elif df.at[i, 'driver_country'] == 'South Africa':
        df.at[i, 'country_lat'] == -30.5595
        df.at[i, 'country_lng'] == 22.9375
    elif df.at[i, 'driver_country'] == 'Austria':
        df.at[i, 'country_lat'] == 48.2082
        df.at[i, 'country_lng'] == 16.3738
    elif df.at[i, 'driver_country'] == 'Argentina':
        df.at[i, 'country_lat'] == -34.6037
        df.at[i, 'country_lng'] == -58.3816
    elif df.at[i, 'driver_country'] == 'American':
        df.at[i, 'country_lat'] == 37.0902
        df.at[i, 'country_lng'] == -95.7129
    elif df.at[i, 'driver_country'] == 'Brazil':
        df.at[i, 'country_lat'] == -14.2350
        df.at[i, 'country_lng'] == -51.9253
    elif df.at[i, 'driver_country'] == 'Colombia':
        df.at[i, 'country_lat'] == 4.5709
        df.at[i, 'country_lng'] == -74.2973
    elif df.at[i, 'driver_country'] == 'Sweden':
        df.at[i, 'country_lat'] == 59.3293
        df.at[i, 'country_lng'] == 18.0686
    elif df.at[i, 'driver_country'] == 'Zimbabwe':
        df.at[i, 'country_lat'] == -19.0154
        df.at[i, 'country_lng'] == 29.1549
    elif df.at[i, 'driver_country'] == 'New Zealand':
        df.at[i, 'country_lat'] == -40.9006
        df.at[i, 'country_lng'] == 174.8860
    elif df.at[i, 'driver_country'] == 'India':
        df.at[i, 'country_lat'] == 28.7041
        df.at[i, 'country_lng'] == 77.1025
    elif df.at[i, 'driver_country'] == 'Portugal':
        df.at[i, 'country_lat'] == 38.7223
        df.at[i, 'country_lng'] == -9.1393
    elif df.at[i, 'driver_country'] == 'Sweden':
        df.at[i, 'country_lat'] == 59.3293
        df.at[i, 'country_lng'] == 18.0686
    elif df.at[i, 'driver_country'] == 'Hungary':
        df.at[i, 'country_lat'] == 47.1625
        df.at[i, 'country_lng'] == 19.5033
    elif df.at[i, 'driver_country'] == 'Venezuela':
        df.at[i, 'country_lat'] == 6.4238
        df.at[i, 'country_lng'] == -66.5897
    elif df.at[i, 'driver_country'] == 'Uruquay':
        df.at[i, 'country_lat'] == -32.5228
        df.at[i, 'country_lng'] == -55.7658
    elif df.at[i, 'driver_country'] == 'Indonesia':
        df.at[i, 'country_lat'] == -0.7893
        df.at[i, 'country_lng'] == 113.9213
    elif df.at[i, 'driver_country'] == 'Ireland':
        df.at[i, 'country_lat'] == 53.1424
        df.at[i, 'country_lng'] == -7.6921
    elif df.at[i, 'driver_country'] == 'Liechtenstein':
        df.at[i, 'country_lat'] == 47.1660
        df.at[i, 'country_lng'] == 9.5554
    elif df.at[i, 'driver_country'] == 'Malaysia':
        df.at[i, 'country_lat'] == 4.2105
        df.at[i, 'country_lng'] == 101.9758
    elif df.at[i, 'driver_country'] == 'Germany':
        df.at[i, 'country_lat'] == 52.5200
        df.at[i, 'country_lng'] == 13.4050
    elif df.at[i, 'driver_country'] == 'Argentina':
        df.at[i, 'country_lat'] == -34.6037
        df.at[i, 'country_lng'] == -58.3816
    elif df.at[i, 'driver_country'] == 'Czech Republic':
        df.at[i, 'country_lat'] 
    elif df.at[i, 'driver_country'] == 'United States':
        df.at[i, 'country_lat'] == 37.0902
        df.at[i, 'country_lng'] == -95.7129
    elif df.at[i, 'driver_country'] == 'Chile':
        df.at[i, 'country_lat'] == -35.6751
        df.at[i, 'country_lng'] == -71.5430




df.head()



Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0             0             0             0             0             0   
1             1             1             1             1             1   
2             2             2             2             2             2   
3             3             3             3             3             3   
4             4             4             4             4             4   

   Unnamed: 0  driverId       dob nationality dob_formatted  ...  \
0           0         1  1/7/1985     British          1985  ...   
1           1         1  1/7/1985     British          1985  ...   
2           2         1  1/7/1985     British          1985  ...   
3           3         1  1/7/1985     British          1985  ...   
4           4         1  1/7/1985     British          1985  ...   

   sprslt_fastestLap  race_lat  race_lng nationality_lat  nationality_lat.1  \
0                5.0   -23.702   -46.698          52.078             52.078   
1                5.0   -23.702   -46.698          52.078             52.078   
2                5.0   -23.702   -46.698          52.078             52.078   
3                5.0   -23.702   -46.698          52.078             52.078   
4                5.0   -23.702   -46.698          52.078             52.078   

   nationality_lat.2  nationality_lat.3  driver_country  country_lat  \
0             52.078             52.078  United Kingdom         None   
1             52.078             52.078  United Kingdom         None   
2             52.078             52.078  United Kingdom         None   
3             52.078             52.078  United Kingdom         None   
4             52.078             52.078  United Kingdom         None   

   country_lng  
0         None  
1         None  
2         None  
3         None  
4         None  

[5 rows x 52 columns]

In [23]:
# drop nationality lat nationality lat1 nationality lat.2 nationality lat.3
df.drop('nationality_lat', axis=1)
df.drop('nationality_lat.1', axis=1)
df.drop('nationality_lat.2', axis=1)
df.drop('nationality_lat.3', axis=1)

df.head()

Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0             0             0             0             0             0   
1             1             1             1             1             1   
2             2             2             2             2             2   
3             3             3             3             3             3   
4             4             4             4             4             4   

   Unnamed: 0  driverId       dob nationality dob_formatted  ...  \
0           0         1  1/7/1985     British          1985  ...   
1           1         1  1/7/1985     British          1985  ...   
2           2         1  1/7/1985     British          1985  ...   
3           3         1  1/7/1985     British          1985  ...   
4           4         1  1/7/1985     British          1985  ...   

   sprslt_fastestLap  race_lat  race_lng nationality_lat  nationality_lat.1  \
0                5.0   -23.702   -46.698          52.078             52.078   
1                5.0   -23.702   -46.698          52.078             52.078   
2                5.0   -23.702   -46.698          52.078             52.078   
3                5.0   -23.702   -46.698          52.078             52.078   
4                5.0   -23.702   -46.698          52.078             52.078   

   nationality_lat.2  nationality_lat.3  driver_country  country_lat  \
0             52.078             52.078  United Kingdom         None   
1             52.078             52.078  United Kingdom         None   
2             52.078             52.078  United Kingdom         None   
3             52.078             52.078  United Kingdom         None   
4             52.078             52.078  United Kingdom         None   

   country_lng  
0         None  
1         None  
2         None  
3         None  
4         None  

[5 rows x 52 columns]

In [24]:
#Count all the number of  latitudes in the country_lat column
df['country_lat'].value_counts()



Series([], Name: country_lat, dtype: int64)

In [25]:
#save changes to final_merged_table.csv
df.to_csv('final_merged_table copy.csv')



In [27]:
# Check data types for columns 'grid', 'results_position', 'results_points', 'results_laps', 'fastestLap', 'rank', 'results_fastestlaptime'
columns = ['grid', 'results_position', 'results_points', 'results_laps', 'fastestLap', 'rank', 'results_fastestlaptime']
df[columns].dtypes

grid                      float64
results_position          float64
results_points            float64
results_laps              float64
fastestLap                float64
rank                      float64
results_fastestlaptime     object
dtype: object

In [28]:
df['grid'].unique()

array([10., 12.,  0.,  4.,  2.,  3.,  8.,  9.,  5., 15., 19., 18.,  7.,
        1.,  6., 14., 17., 16., 13., 11., nan])

In [29]:
df['results_position'].unique()

array([ 1.,  9., 12.,  4.,  2.,  6.,  8., 11., 10., 15., 17., 18., nan,
        5., 13.,  7., 16.,  3., 14.])

In [30]:
df['results_points'].unique()

array([25.,  2.,  0., 13., 18.,  8.,  4.,  1., 19., 10.,  6., 12., 15.,
       26., nan])

In [31]:
df['results_laps'].unique()

array([71., 70., 69., 56., 48., 50., 24., 52., 51., 40., 53., 25., 41.,
       49., 47., 62., 63., nan])

In [32]:
df['fastestLap'].unique()

array([46., 37., 54., 71., 47., 63., 48., 69., 53., 62., 36., 66., 61.,
       55., 64., 60., 14., 50., 65., 59.,  5., 45., 35., 51., 49., 52.,
       44.,  3., 41., 34., 25., 40., 57., 43., nan])

In [33]:
df['rank'].unique()

array([ 2., 12.,  5.,  1.,  3.,  6., 16.,  9., 10., 13., 19., 11., 14.,
        4., 17., 18.,  8., 15.,  7., 20., nan])

In [34]:
df['results_fastestlaptime'].unique()

array(['01:12.0', '01:13.9', '01:12.6', '01:11.0', '01:12.5', '01:12.7',
       '01:14.4', '01:13.6', '01:13.8', '01:14.2', '01:15.0', '01:09.9',
       '01:07.3', '01:08.6', '01:09.6', '01:10.0', '01:10.1', '01:07.6',
       '01:09.3', '01:09.1', '01:09.7', '01:10.9', '01:15.5', '01:14.3',
       '01:14.0', '01:15.1', '01:14.8', '01:15.3', '01:15.9', '01:15.8',
       '01:09.0', '01:11.8', '01:09.4', '01:29.7', '01:31.7', '01:31.9',
       '01:33.1', '01:28.6', '01:31.3', '01:30.5', '01:31.2', '01:32.2',
       '01:32.0', '01:32.3', '01:30.3', '01:30.6', '01:31.4', '01:32.5',
       '01:30.8', '01:32.9', '01:25.9', '01:25.5', '01:25.8', '01:25.2',
       '01:24.8', '01:25.7', '01:25.3', '01:25.0', '01:26.0', '01:27.2',
       '01:25.6', '01:26.7', '01:13.2', '01:12.8', '01:14.6', '01:21.4',
       '01:21.2', '01:18.9', '01:21.6', '01:20.8', '01:18.4', '01:21.9',
       '01:21.8', '01:21.7', '01:18.6', '01:20.9', '01:21.0', '01:21.3',
       '01:20.5', '01:19.0', '01:15.6', nan], dtype

In [35]:
# drop na for columns 'results_fastestlaptime'
df = df.dropna(subset=['results_fastestlaptime'])


# Convert results_fastestlaptime to datetime
df['results_fastestlaptime'] = pd.to_datetime(df['results_fastestlaptime'], format='%M:%S.%f')

/var/folders/7t/kx7mpsk15210p47h__d0lpt80000gn/T/ipykernel_30482/2556191723.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['results_fastestlaptime'] = pd.to_datetime(df['results_fastestlaptime'], format='%M:%S.%f')


In [36]:
df.shape

(16057, 52)