In [1]:
# Import libraries for machine learning, pandas, and numpy
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression




In [2]:
# Load data from final_merged_table.csv
df = pd.read_csv('../outer_join_final_viz.csv')

/var/folders/7t/kx7mpsk15210p47h__d0lpt80000gn/T/ipykernel_14968/4234936246.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../outer_join_final_viz.csv')


In [3]:
# list columns 
df.columns

Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder', 'results_points',
       'results_laps', 'fastestLap', 'rank', 'race_ms',
       'results_fastestlaptime', 'fastestLapSpeed', 'statusId', 'status',
       'year', 'round', 'circuitId', 'races_name', 'date', 'dstnd_points',
       'dstnd_position', 'wins', 'lapt_lap', 'lapt_position', 'lap_ms',
       'quali_position'],
      dtype='object')

In [4]:
# list all driver ids in driver id column
df['driverId'].unique()

array([  1,   2,   3,   4,   5,   6,   8,   7,   9,  10,  11,  13,  14,
        12,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  27,
        29,  30,  31,  32,  33,  35,  37,  39,  40,  41,  26,  42,  43,
        44,  46,  45,  47,  48,  49,  50,  51,  52,  53,  55,  56,  34,
        57,  36,  38,  58,  61,  62,  63,  64,  65,  67,  68,  69,  71,
        73,  74,  75,  76,  77,  59,  66,  78,  79,  81,  82,  83,  84,
        85, 153, 154, 155, 807, 808, 810, 811, 812, 813, 814, 815, 817,
       816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829,
       830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842,
       843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855,
       856,  60,  70, 251, 106, 681, 285, 120, 264, 802, 664, 601, 647,
       497, 452, 496, 455, 630, 209, 665, 276, 606, 577, 801, 599, 550,
       756, 151, 384, 253, 700, 399, 119, 270, 437, 620, 518, 549, 268,
       310, 214, 397, 101, 339, 486, 330, 359, 213, 137, 745, 26

In [5]:
# count of wins for driverID 11
df[df['driverId'] == 11]['wins'].sum()

0.0

In [6]:
df['year'].unique()

array([2009., 2010., 2012., 2013., 2014., 2008., 2007., 2011., 2015.,
       2016., 2017., 2018., 2019., 2020., 2021., 2022., 2006., 2005.,
       2004., 2003., 2002., 2001., 2000., 1998., 1997., 1996., 1999.,
         nan])

In [7]:
df[df['driverId']==1]['wins'].count()

17625

In [8]:
df[df['driverId']==4]['wins'].sum()

20176.0

In [9]:
# List race names
df['races_name'].unique()

array(['Malaysian Grand Prix', 'Italian Grand Prix',
       'Singapore Grand Prix', 'Abu Dhabi Grand Prix',
       'Bahrain Grand Prix', 'German Grand Prix', 'Indian Grand Prix',
       'United States Grand Prix', 'Chinese Grand Prix',
       'Australian Grand Prix', 'Spanish Grand Prix', 'Monaco Grand Prix',
       'British Grand Prix', 'Hungarian Grand Prix', 'Belgian Grand Prix',
       'Korean Grand Prix', 'Japanese Grand Prix', 'Brazilian Grand Prix',
       'Turkish Grand Prix', 'Canadian Grand Prix', 'French Grand Prix',
       'Austrian Grand Prix', 'European Grand Prix', 'Russian Grand Prix',
       'Mexican Grand Prix', 'Azerbaijan Grand Prix', 'Eifel Grand Prix',
       'Emilia Romagna Grand Prix', 'Portuguese Grand Prix',
       'Miami Grand Prix', 'Styrian Grand Prix', 'Tuscan Grand Prix',
       'Qatar Grand Prix', 'Mexico City Grand Prix',
       'San Marino Grand Prix', 'Dutch Grand Prix',
       'São Paulo Grand Prix', 'Saudi Arabian Grand Prix',
       '70th Anniversa

In [10]:
# count of results laps from driver id 10
df[df['driverId']==10]['results_laps'].count()

4705

In [11]:
df[df['driverId']==10]['results_laps'].sum()

270753.0

In [12]:
#Show all dates in date column in descending order
df['date'].sort_values(ascending=False)


373207    2022-11-20
373221    2022-11-20
373211    2022-11-20
373212    2022-11-20
373213    2022-11-20
             ...    
449484           NaN
449485           NaN
449486           NaN
449487           NaN
449488           NaN
Name: date, Length: 449489, dtype: object

In [13]:
df.columns

Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder', 'results_points',
       'results_laps', 'fastestLap', 'rank', 'race_ms',
       'results_fastestlaptime', 'fastestLapSpeed', 'statusId', 'status',
       'year', 'round', 'circuitId', 'races_name', 'date', 'dstnd_points',
       'dstnd_position', 'wins', 'lapt_lap', 'lapt_position', 'lap_ms',
       'quali_position'],
      dtype='object')

In [14]:
df.head()

driverId       dob nationality dob_formatted  raceId  grid  \
0         1  1/7/1985     British          1985     2.0  12.0   
1         1  1/7/1985     British          1985    13.0   1.0   
2         1  1/7/1985     British          1985    13.0   1.0   
3         1  1/7/1985     British          1985    13.0   1.0   
4         1  1/7/1985     British          1985    13.0   1.0   

   results_position positionText  positionOrder  results_points  ...  \
0               7.0            7            7.0             1.0  ...   
1              12.0           12           12.0             0.0  ...   
2              12.0           12           12.0             0.0  ...   
3              12.0           12           12.0             0.0  ...   
4              12.0           12           12.0             0.0  ...   

   circuitId            races_name        date  dstnd_points dstnd_position  \
0        2.0  Malaysian Grand Prix  2009-04-05           1.0           10.0   
1       14.0    Italian Grand Prix  2009-09-13          27.0            7.0   
2       14.0    Italian Grand Prix  2009-09-13          27.0            7.0   
3       14.0    Italian Grand Prix  2009-09-13          27.0            7.0   
4       14.0    Italian Grand Prix  2009-09-13          27.0            7.0   

   wins  lapt_lap lapt_position   lap_ms  quali_position  
0   0.0      19.0           6.0  99460.0            13.0  
1   1.0      17.0           5.0  86358.0             1.0  
2   1.0      50.0           3.0  84958.0             1.0  
3   1.0      49.0           3.0  85197.0             1.0  
4   1.0      48.0           3.0  85076.0             1.0  

[5 rows x 30 columns]

In [15]:
# Show all driver id's that have a qualifications position of 1 or more
# df[df['quali_position'] >= 1]['driverId'].unique()

In [16]:
# drop race long column at the end of the table
df.drop(df.columns[[len(df.columns)-1]], axis=1, inplace=True)
df

driverId        dob nationality dob_formatted  raceId  grid  \
0              1   1/7/1985     British          1985     2.0  12.0   
1              1   1/7/1985     British          1985    13.0   1.0   
2              1   1/7/1985     British          1985    13.0   1.0   
3              1   1/7/1985     British          1985    13.0   1.0   
4              1   1/7/1985     British          1985    13.0   1.0   
...          ...        ...         ...           ...     ...   ...   
449484       263  5/17/1948     Finnish          1948     NaN   NaN   
449485       616  7/15/1928    American          1928     NaN   NaN   
449486       615  8/21/1913    American          1913     NaN   NaN   
449487       144  6/13/1966    Japanese          1966     NaN   NaN   
449488       453  11/1/1936     British          1936     NaN   NaN   

        results_position positionText  positionOrder  results_points  ...  \
0                    7.0            7            7.0             1.0  ...   
1                   12.0           12           12.0             0.0  ...   
2                   12.0           12           12.0             0.0  ...   
3                   12.0           12           12.0             0.0  ...   
4                   12.0           12           12.0             0.0  ...   
...                  ...          ...            ...             ...  ...   
449484               NaN          NaN            NaN             NaN  ...   
449485               NaN          NaN            NaN             NaN  ...   
449486               NaN          NaN            NaN             NaN  ...   
449487               NaN          NaN            NaN             NaN  ...   
449488               NaN          NaN            NaN             NaN  ...   

        round  circuitId            races_name        date dstnd_points  \
0         2.0        2.0  Malaysian Grand Prix  2009-04-05          1.0   
1        13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
2        13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
3        13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
4        13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
...       ...        ...                   ...         ...          ...   
449484    NaN        NaN                   NaN         NaN          NaN   
449485    NaN        NaN                   NaN         NaN          NaN   
449486    NaN        NaN                   NaN         NaN          NaN   
449487    NaN        NaN                   NaN         NaN          NaN   
449488    NaN        NaN                   NaN         NaN          NaN   

        dstnd_position  wins lapt_lap  lapt_position   lap_ms  
0                 10.0   0.0     19.0            6.0  99460.0  
1                  7.0   1.0     17.0            5.0  86358.0  
2                  7.0   1.0     50.0            3.0  84958.0  
3                  7.0   1.0     49.0            3.0  85197.0  
4                  7.0   1.0     48.0            3.0  85076.0  
...                ...   ...      ...            ...      ...  
449484             NaN   NaN      NaN            NaN      NaN  
449485             NaN   NaN      NaN            NaN      NaN  
449486             NaN   NaN      NaN            NaN      NaN  
449487             NaN   NaN      NaN            NaN      NaN  
449488             NaN   NaN      NaN            NaN      NaN  

[449489 rows x 29 columns]

In [17]:
df['races_name'].unique()

array(['Malaysian Grand Prix', 'Italian Grand Prix',
       'Singapore Grand Prix', 'Abu Dhabi Grand Prix',
       'Bahrain Grand Prix', 'German Grand Prix', 'Indian Grand Prix',
       'United States Grand Prix', 'Chinese Grand Prix',
       'Australian Grand Prix', 'Spanish Grand Prix', 'Monaco Grand Prix',
       'British Grand Prix', 'Hungarian Grand Prix', 'Belgian Grand Prix',
       'Korean Grand Prix', 'Japanese Grand Prix', 'Brazilian Grand Prix',
       'Turkish Grand Prix', 'Canadian Grand Prix', 'French Grand Prix',
       'Austrian Grand Prix', 'European Grand Prix', 'Russian Grand Prix',
       'Mexican Grand Prix', 'Azerbaijan Grand Prix', 'Eifel Grand Prix',
       'Emilia Romagna Grand Prix', 'Portuguese Grand Prix',
       'Miami Grand Prix', 'Styrian Grand Prix', 'Tuscan Grand Prix',
       'Qatar Grand Prix', 'Mexico City Grand Prix',
       'San Marino Grand Prix', 'Dutch Grand Prix',
       'São Paulo Grand Prix', 'Saudi Arabian Grand Prix',
       '70th Anniversa

In [18]:
# Create a dictionary to show countries for the races 'Malaysian Grand Prix', 'Italian Grand Prix',
    #    'Singapore Grand Prix', 'Abu Dhabi Grand Prix',
    #    'Bahrain Grand Prix', 'German Grand Prix', 'Indian Grand Prix',
    #    'United States Grand Prix', 'Chinese Grand Prix',
    #    'Australian Grand Prix', 'Spanish Grand Prix', 'Monaco Grand Prix',
    #    'British Grand Prix', 'Hungarian Grand Prix', 'Belgian Grand Prix',
    #    'Korean Grand Prix', 'Japanese Grand Prix', 'Brazilian Grand Prix',
    #    'Turkish Grand Prix', 'Canadian Grand Prix', 'French Grand Prix',
    #    'Austrian Grand Prix', 'European Grand Prix', 'Russian Grand Prix',
    #    'Mexican Grand Prix', 'Azerbaijan Grand Prix', 'Eifel Grand Prix',
    #    'Emilia Romagna Grand Prix', 'Portuguese Grand Prix',
    #    'Miami Grand Prix', 'Styrian Grand Prix', 'Tuscan Grand Prix',
    #    'Qatar Grand Prix', 'Mexico City Grand Prix',
    #    'San Marino Grand Prix', 'Dutch Grand Prix',
    #    'São Paulo Grand Prix', 'Saudi Arabian Grand Prix',
    #    '70th Anniversary Grand Prix', 'Sakhir Grand Prix'

# Define the mapping between race name and country
race_country_map = {
    'Malaysian Grand Prix': 'Malaysia', 'Italian Grand Prix': 'Italy', 'Singapore Grand Prix': 'Singapore', 'Abu Dhabi Grand Prix': 'United Arab Emirates', 
    'Bahrain Grand Prix': 'Bahrain', 'German Grand Prix': 'Germany', 'Indian Grand Prix': 'India', 'United States Grand Prix': 'United States',
    'Chinese Grand Prix': 'China', 'Australian Grand Prix': 'Australia', 'Spanish Grand Prix': 'Spain', 'Monaco Grand Prix': 'Monaco',
    'British Grand Prix': 'United Kingdom', 'Hungarian Grand Prix': 'Hungary', 'Belgian Grand Prix': 'Belgium', 'Korean Grand Prix': 'South Korea',
    'Japanese Grand Prix': 'Japan', 'Brazilian Grand Prix': 'Brazil', 'Turkish Grand Prix': 'Turkey', 'Canadian Grand Prix': 'Canada',
    'French Grand Prix': 'France', 'Austrian Grand Prix': 'Austria', 'European Grand Prix': 'Europe', 'Russian Grand Prix': 'Russia',
    'Mexican Grand Prix': 'Mexico', 'Azerbaijan Grand Prix': 'Azerbaijan', 'Eifel Grand Prix': 'Germany', 'Emilia Romagna Grand Prix': 'Italy',
    'Portuguese Grand Prix': 'Portugal', 'Miami Grand Prix': 'United States', 'Styrian Grand Prix': 'Austria', 'Tuscan Grand Prix': 'Italy',
    'Qatar Grand Prix': 'Qatar', 'Mexico City Grand Prix': 'Mexico', 'San Marino Grand Prix': 'Italy', 'Dutch Grand Prix': 'Netherlands',
    'São Paulo Grand Prix': 'Brazil', 'Saudi Arabian Grand Prix': 'Saudi Arabia', '70th Anniversary Grand Prix': 'United Kingdom',
    'Sakhir Grand Prix': 'Bahrain', 'Argentine Grand Prix': 'Argentina'
      
}

# Create a new column in the data frame and populate it with the corresponding country
df['race_country'] = df['races_name'].apply(lambda x: race_country_map.get(x, 'Unknown'))

# Show the race_country and races_name columns only
df[['races_name', 'race_country']]


races_name race_country
0       Malaysian Grand Prix     Malaysia
1         Italian Grand Prix        Italy
2         Italian Grand Prix        Italy
3         Italian Grand Prix        Italy
4         Italian Grand Prix        Italy
...                      ...          ...
449484                   NaN      Unknown
449485                   NaN      Unknown
449486                   NaN      Unknown
449487                   NaN      Unknown
449488                   NaN      Unknown

[449489 rows x 2 columns]

In [19]:
df['nationality'].unique()

array(['British', 'German', 'Spanish', 'Finnish', 'Japanese', 'French',
       'Polish', 'Brazilian', 'Italian', 'Australian', 'Austrian',
       'Dutch', 'Colombian', 'Portuguese', 'Canadian', 'Indian',
       'American', 'Hungarian', 'Irish', 'Danish', 'Czech', 'Malaysian',
       'Swiss', 'Argentine', 'Russian', 'Venezuelan', 'Mexican',
       'Belgian', 'Swedish', 'Indonesian', 'New Zealander', 'Monegasque',
       'Thai', 'Chinese', 'South African', 'Rhodesian', 'Uruguayan',
       'Liechtensteiner', 'East German', 'Chilean', 'Argentine-Italian',
       'American-Italian'], dtype=object)

In [20]:
# Add countries in dictionary called mapping for these nationalities 
# 'British', 'German', 'Spanish', 'Finnish', 'Japanese', 'French',
    #    'Polish', 'Brazilian', 'Italian', 'Australian', 'Austrian',
    #    'Dutch', 'Colombian', 'Portuguese', 'Canadian', 'Indian',
    #    'American', 'Hungarian', 'Irish', 'Danish', 'Czech', 'Malaysian',
    #    'Swiss', 'Argentine', 'Russian', 'Venezuelan', 'Mexican',
    #    'Belgian', 'Swedish', 'Indonesian', 'New Zealander', 'Monegasque',
    #    'Thai', 'Chinese', 'South African', 'Rhodesian', 'Uruguayan',
    #    'Liechtensteiner', 'East German', 'Chilean', 'Argentine-Italian',
    #    'American-Italian'


mapping = { 'British' : 'Unitied Kingdom', 'German' : 'Germany', 'Spanish' : 'Spain', 'Finnish' : 'Finland', 'Japanese' : 'Japan', 'French' : 'France',
         'Polish' : 'Poland', 'Brazilian' : 'Brazil', 'Italian' : 'Italy', 'Australian' : 'Australia', 'Austrian' : 'Austria',
            'Dutch' : 'Netherlands', 'Colombian' : 'Colombia', 'Portuguese' : 'Portugal', 'Canadian' : 'Canada', 'Indian' : 'India',
            'American' : 'United States', 'Hungarian' : 'Hungary', 'Irish' : 'Ireland', 'Danish' : 'Denmark', 'Czech' : 'Czech Republic', 'Malaysian' : 'Malaysia',
            'Swiss' : 'Switzerland', 'Argentine' : 'Argentina', 'Russian' : 'Russia', 'Venezuelan' : 'Venezuela', 'Mexican' : 'Mexico',
            'Belgian' : 'Belgium', 'Swedish' : 'Sweden', 'Indonesian' : 'Indonesia', 'New Zealander' : 'New Zealand', 'Monegasque' : 'Monaco',
            'Thai' : 'Thailand', 'Chinese' : 'China', 'South African' : 'South Africa', 'Rhodesian' : 'Rhodesia', 'Uruguayan' : 'Uruguay',
            'Liechtensteiner' : 'Liechtenstein', 'East German' : 'East Germany', 'Chilean' : 'Chile', 'Argentine-Italian' : 'Argentina',
            'American-Italian' : 'United States'}
df['driver_country'] = df['nationality'].map(mapping)

#Inspect new driver_country column to make sure it matches nationality column
df[['nationality', 'driver_country']].head()
    

nationality   driver_country
0     British  Unitied Kingdom
1     British  Unitied Kingdom
2     British  Unitied Kingdom
3     British  Unitied Kingdom
4     British  Unitied Kingdom

In [21]:
df['driver_country'].unique()

array(['Unitied Kingdom', 'Germany', 'Spain', 'Finland', 'Japan',
       'France', 'Poland', 'Brazil', 'Italy', 'Australia', 'Austria',
       'Netherlands', 'Colombia', 'Portugal', 'Canada', 'India',
       'United States', 'Hungary', 'Ireland', 'Denmark', 'Czech Republic',
       'Malaysia', 'Switzerland', 'Argentina', 'Russia', 'Venezuela',
       'Mexico', 'Belgium', 'Sweden', 'Indonesia', 'New Zealand',
       'Monaco', 'Thailand', 'China', 'South Africa', 'Rhodesia',
       'Uruguay', 'Liechtenstein', 'East Germany', 'Chile'], dtype=object)

In [22]:
df['grid'].unique()

array([12.,  1.,  4.,  6.,  2.,  3.,  9.,  5., 14., 19., 16., 18., 13.,
       20., 15., 22., 10., 17., 11.,  8.,  7., 24., 21.,  0., 23., nan])

In [23]:
df['results_position'].unique()

array([ 7., 12.,  1., nan,  3.,  4.,  2.,  6.,  5.,  9., 13., 16., 18.,
       10.,  8., 14., 19., 15., 11., 17., 20., 21., 22., 23., 24.])

In [24]:
df['results_points'].unique()

array([ 1. ,  0. , 10. , 15. , 12. , 18. , 25. ,  3. ,  5. ,  2. ,  8. ,
        6. ,  4. , 50. ,  7. , 26. , 19. , 16. ,  7.5,  0.5, 36. , 20. ,
       11. ,  2.5,  1.5, 13. ,  9. , 30. , 12.5,  nan])

In [25]:
df['results_laps'].unique()

array([31., 52., 61., 20., 49., 67., 55., 60., 56., 57., 58., 65., 78.,
       77., 70., 44., 53.,  7., 71.,  2., 59., 66., 76., 19., 54., 46.,
       38., 73., 12., 30., 64., 43., 51., 23., 35., 69., 32., 40., 68.,
       22., 63., 62., 28., 48.,  9., 72., 25., 50., 29., 33., 75., 21.,
       42., 36., 27.,  1.,  6., 15., 47., 18.,  8., 26., 41., 17., 13.,
       37., 11., 16., 45., 24.,  3., 10., 87., 34., 39.,  5.,  0., 14.,
        4., 74., nan])

In [26]:
df['fastestLap'].unique()

array([17., 52., 36., 16., 42., 65., 47., 58., 55., 39., 13., 45., 32.,
       50., 48., 53., 76., 51., 29., 57., 69., 59.,  3.,  2., 49., 24.,
       46., 25., 20., 31., 71.,  4., 40., 54., 34., 41., 26., 15., 14.,
       33., 62., 22., 18., 11., 27., 38.,  7., 61., 28.,  8., 37., 68.,
       64., 60., 56., 43., 35., 66., 44., 67., 63., 23., 30., 19., 70.,
        9., 72., 10., nan,  6., 21., 74.,  5., 73., 77., 12., 78., 75.,
       80., 85.])

In [27]:
df['rank'].unique()

array([11.,  3.,  2.,  4.,  5.,  1., 12.,  6., 10., 13.,  9.,  8.,  7.,
       20., 15., 18., 19., 23., 14., 16., nan, 17.,  0., 22., 21., 24.])

In [28]:
df['results_fastestlaptime'].unique()

array(['01:39.1', '01:24.8', '01:48.3', '01:40.4', '01:59.6', '01:16.5',
       '01:41.3', '01:28.9', '01:39.7', '01:54.7', '01:34.9', '01:29.8',
       '01:41.0', '01:40.0', '01:38.2', '01:27.9', '01:18.1', '01:34.2',
       '01:23.8', '01:15.7', '01:24.6', '01:51.6', '01:25.8', '01:49.9',
       '01:42.5', '01:41.2', '01:29.1', '01:45.5', '01:16.7', '01:43.1',
       '01:37.1', '01:28.6', '01:22.6', '01:35.4', '01:22.5', '01:35.5',
       '01:22.0', '01:26.5', '01:18.5', '01:17.5', '01:32.8', '01:29.5',
       '01:19.4', '01:18.9', '01:12.2', '01:37.2', '01:19.9', '01:16.0',
       '01:21.5', '01:38.9', '01:48.1', '01:29.7', '01:46.1', '01:19.6',
       '01:27.4', '01:53.7', '01:28.0', '01:50.4', '01:41.6', '01:41.9',
       '01:13.6', '01:45.6', '01:36.3', '01:14.2', '01:26.4', '01:36.7',
       '01:34.3', '01:22.9', '01:13.2', '01:16.6', '01:21.7', '01:33.4',
       '01:28.2', '01:30.3', '01:41.5', '01:30.1', '01:30.9', '01:42.2',
       '01:37.9', '01:28.3', '01:18.7', '01:26.7', 

In [29]:
df['driverId'].unique()

array([  1,   2,   3,   4,   5,   6,   8,   7,   9,  10,  11,  13,  14,
        12,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  27,
        29,  30,  31,  32,  33,  35,  37,  39,  40,  41,  26,  42,  43,
        44,  46,  45,  47,  48,  49,  50,  51,  52,  53,  55,  56,  34,
        57,  36,  38,  58,  61,  62,  63,  64,  65,  67,  68,  69,  71,
        73,  74,  75,  76,  77,  59,  66,  78,  79,  81,  82,  83,  84,
        85, 153, 154, 155, 807, 808, 810, 811, 812, 813, 814, 815, 817,
       816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829,
       830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842,
       843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855,
       856,  60,  70, 251, 106, 681, 285, 120, 264, 802, 664, 601, 647,
       497, 452, 496, 455, 630, 209, 665, 276, 606, 577, 801, 599, 550,
       756, 151, 384, 253, 700, 399, 119, 270, 437, 620, 518, 549, 268,
       310, 214, 397, 101, 339, 486, 330, 359, 213, 137, 745, 26

In [30]:
df['year'].unique() 

array([2009., 2010., 2012., 2013., 2014., 2008., 2007., 2011., 2015.,
       2016., 2017., 2018., 2019., 2020., 2021., 2022., 2006., 2005.,
       2004., 2003., 2002., 2001., 2000., 1998., 1997., 1996., 1999.,
         nan])

In [31]:

df.columns


Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder', 'results_points',
       'results_laps', 'fastestLap', 'rank', 'race_ms',
       'results_fastestlaptime', 'fastestLapSpeed', 'statusId', 'status',
       'year', 'round', 'circuitId', 'races_name', 'date', 'dstnd_points',
       'dstnd_position', 'wins', 'lapt_lap', 'lapt_position', 'lap_ms',
       'race_country', 'driver_country'],
      dtype='object')

In [32]:
# # save to csv
# df.to_csv('../VisualizationDF.csv', index=False)
df.to_csv('outer_join_table_viz.csv', index=False)

In [33]:
# Drop lapt_position and lapt_lap columns
df = df.drop(['lapt_position', 'lapt_lap'], axis=1)

df.columns


Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder', 'results_points',
       'results_laps', 'fastestLap', 'rank', 'race_ms',
       'results_fastestlaptime', 'fastestLapSpeed', 'statusId', 'status',
       'year', 'round', 'circuitId', 'races_name', 'date', 'dstnd_points',
       'dstnd_position', 'wins', 'lap_ms', 'race_country', 'driver_country'],
      dtype='object')

In [34]:

# Rename columns
df = df.rename(columns={
    'results_points': 'total_results_points',
     'race_ms': 'race_minutes',
     'lap_ms': 'avg_lap_time',
})

df

driverId        dob nationality dob_formatted  raceId  grid  \
0              1   1/7/1985     British          1985     2.0  12.0   
1              1   1/7/1985     British          1985    13.0   1.0   
2              1   1/7/1985     British          1985    13.0   1.0   
3              1   1/7/1985     British          1985    13.0   1.0   
4              1   1/7/1985     British          1985    13.0   1.0   
...          ...        ...         ...           ...     ...   ...   
449484       263  5/17/1948     Finnish          1948     NaN   NaN   
449485       616  7/15/1928    American          1928     NaN   NaN   
449486       615  8/21/1913    American          1913     NaN   NaN   
449487       144  6/13/1966    Japanese          1966     NaN   NaN   
449488       453  11/1/1936     British          1936     NaN   NaN   

        results_position positionText  positionOrder  total_results_points  \
0                    7.0            7            7.0                   1.0   
1                   12.0           12           12.0                   0.0   
2                   12.0           12           12.0                   0.0   
3                   12.0           12           12.0                   0.0   
4                   12.0           12           12.0                   0.0   
...                  ...          ...            ...                   ...   
449484               NaN          NaN            NaN                   NaN   
449485               NaN          NaN            NaN                   NaN   
449486               NaN          NaN            NaN                   NaN   
449487               NaN          NaN            NaN                   NaN   
449488               NaN          NaN            NaN                   NaN   

        ...  round  circuitId            races_name        date dstnd_points  \
0       ...    2.0        2.0  Malaysian Grand Prix  2009-04-05          1.0   
1       ...   13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
2       ...   13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
3       ...   13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
4       ...   13.0       14.0    Italian Grand Prix  2009-09-13         27.0   
...     ...    ...        ...                   ...         ...          ...   
449484  ...    NaN        NaN                   NaN         NaN          NaN   
449485  ...    NaN        NaN                   NaN         NaN          NaN   
449486  ...    NaN        NaN                   NaN         NaN          NaN   
449487  ...    NaN        NaN                   NaN         NaN          NaN   
449488  ...    NaN        NaN                   NaN         NaN          NaN   

        dstnd_position  wins avg_lap_time  race_country   driver_country  
0                 10.0   0.0      99460.0      Malaysia  Unitied Kingdom  
1                  7.0   1.0      86358.0         Italy  Unitied Kingdom  
2                  7.0   1.0      84958.0         Italy  Unitied Kingdom  
3                  7.0   1.0      85197.0         Italy  Unitied Kingdom  
4                  7.0   1.0      85076.0         Italy  Unitied Kingdom  
...                ...   ...          ...           ...              ...  
449484             NaN   NaN          NaN       Unknown          Finland  
449485             NaN   NaN          NaN       Unknown    United States  
449486             NaN   NaN          NaN       Unknown    United States  
449487             NaN   NaN          NaN       Unknown            Japan  
449488             NaN   NaN          NaN       Unknown  Unitied Kingdom  

[449489 rows x 29 columns]

In [35]:
df.columns

Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder',
       'total_results_points', 'results_laps', 'fastestLap', 'rank',
       'race_minutes', 'results_fastestlaptime', 'fastestLapSpeed', 'statusId',
       'status', 'year', 'round', 'circuitId', 'races_name', 'date',
       'dstnd_points', 'dstnd_position', 'wins', 'avg_lap_time',
       'race_country', 'driver_country'],
      dtype='object')

In [36]:


# Adjust avg_lap_time  to represent the average lap time for the driverID who raced at the raceID in the year
# Calculate the average lap time for each race_id, driverId, and year
df = df.groupby(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder',
       'total_results_points', 'results_laps', 'fastestLap', 'rank',
       'race_minutes', 'results_fastestlaptime', 'fastestLapSpeed', 'statusId',
       'status', 'year', 'round', 'circuitId', 'races_name', 'date',
       'dstnd_points', 'dstnd_position', 'wins', 'driver_country',
       'race_country']).agg({"avg_lap_time": "mean"}).reset_index()

# Check driverID, year, raceID, and avg_lap_time
df[['driverId', 'year', 'raceId', 'avg_lap_time']].head()


driverId    year  raceId   avg_lap_time
0         1  2009.0     2.0  109398.548387
1         1  2009.0     3.0  127416.982143
2         1  2009.0     4.0   97022.421053
3         1  2009.0     7.0   90781.068966
4         1  2009.0    10.0   84341.085714

In [37]:
df['year'].unique()


array([2009., 2008., 2007., 2010., 2011., 2012., 2013., 2014., 2015.,
       2016., 2017., 2018., 2019., 2020., 2021., 2022., 2006., 2005.,
       2004.])

In [38]:
df.head(10)

driverId       dob nationality dob_formatted  raceId  grid  \
0         1  1/7/1985     British          1985     2.0  12.0   
1         1  1/7/1985     British          1985     3.0   9.0   
2         1  1/7/1985     British          1985     4.0   5.0   
3         1  1/7/1985     British          1985     7.0  16.0   
4         1  1/7/1985     British          1985    10.0   4.0   
5         1  1/7/1985     British          1985    11.0   1.0   
6         1  1/7/1985     British          1985    14.0   1.0   
7         1  1/7/1985     British          1985    15.0   3.0   
8         1  1/7/1985     British          1985    16.0  17.0   
9         1  1/7/1985     British          1985    18.0   1.0   

   results_position positionText  positionOrder  total_results_points  ...  \
0               7.0            7            7.0                   1.0  ...   
1               6.0            6            6.0                   3.0  ...   
2               4.0            4            4.0                   5.0  ...   
3              13.0           13           13.0                   0.0  ...   
4               1.0            1            1.0                  10.0  ...   
5               2.0            2            2.0                   8.0  ...   
6               1.0            1            1.0                  10.0  ...   
7               3.0            3            3.0                   6.0  ...   
8               3.0            3            3.0                   6.0  ...   
9               1.0            1            1.0                  10.0  ...   

   round  circuitId             races_name        date dstnd_points  \
0    2.0        2.0   Malaysian Grand Prix  2009-04-05          1.0   
1    3.0       17.0     Chinese Grand Prix  2009-04-19          4.0   
2    4.0        3.0     Bahrain Grand Prix  2009-04-26          9.0   
3    7.0        5.0     Turkish Grand Prix  2009-06-07          9.0   
4   10.0       11.0   Hungarian Grand Prix  2009-07-26         19.0   
5   11.0       12.0    European Grand Prix  2009-08-23         27.0   
6   14.0       15.0   Singapore Grand Prix  2009-09-27         37.0   
7   15.0       22.0    Japanese Grand Prix  2009-10-04         43.0   
8   16.0       18.0   Brazilian Grand Prix  2009-10-18         49.0   
9    1.0        1.0  Australian Grand Prix  2008-03-16         10.0   

   dstnd_position  wins   driver_country  race_country   avg_lap_time  
0            10.0   0.0  Unitied Kingdom      Malaysia  109398.548387  
1            10.0   0.0  Unitied Kingdom         China  127416.982143  
2             7.0   0.0  Unitied Kingdom       Bahrain   97022.421053  
3            11.0   0.0  Unitied Kingdom        Turkey   90781.068966  
4             8.0   1.0  Unitied Kingdom       Hungary   84341.085714  
5             6.0   1.0  Unitied Kingdom        Europe  100941.175439  
6             6.0   2.0  Unitied Kingdom     Singapore  114202.245902  
7             6.0   2.0  Unitied Kingdom         Japan  100130.471698  
8             5.0   2.0  Unitied Kingdom        Brazil   78338.380282  
9             1.0   1.0  Unitied Kingdom     Australia   98114.068966  

[10 rows x 29 columns]

In [39]:
# Change race_minutes to race_time
df = df.rename(columns={
    'race_minutes': 'race_time',
})
df.columns

Index(['driverId', 'dob', 'nationality', 'dob_formatted', 'raceId', 'grid',
       'results_position', 'positionText', 'positionOrder',
       'total_results_points', 'results_laps', 'fastestLap', 'rank',
       'race_time', 'results_fastestlaptime', 'fastestLapSpeed', 'statusId',
       'status', 'year', 'round', 'circuitId', 'races_name', 'date',
       'dstnd_points', 'dstnd_position', 'wins', 'driver_country',
       'race_country', 'avg_lap_time'],
      dtype='object')

In [40]:
df.head()

driverId       dob nationality dob_formatted  raceId  grid  \
0         1  1/7/1985     British          1985     2.0  12.0   
1         1  1/7/1985     British          1985     3.0   9.0   
2         1  1/7/1985     British          1985     4.0   5.0   
3         1  1/7/1985     British          1985     7.0  16.0   
4         1  1/7/1985     British          1985    10.0   4.0   

   results_position positionText  positionOrder  total_results_points  ...  \
0               7.0            7            7.0                   1.0  ...   
1               6.0            6            6.0                   3.0  ...   
2               4.0            4            4.0                   5.0  ...   
3              13.0           13           13.0                   0.0  ...   
4               1.0            1            1.0                  10.0  ...   

   round  circuitId            races_name        date dstnd_points  \
0    2.0        2.0  Malaysian Grand Prix  2009-04-05          1.0   
1    3.0       17.0    Chinese Grand Prix  2009-04-19          4.0   
2    4.0        3.0    Bahrain Grand Prix  2009-04-26          9.0   
3    7.0        5.0    Turkish Grand Prix  2009-06-07          9.0   
4   10.0       11.0  Hungarian Grand Prix  2009-07-26         19.0   

   dstnd_position  wins   driver_country  race_country   avg_lap_time  
0            10.0   0.0  Unitied Kingdom      Malaysia  109398.548387  
1            10.0   0.0  Unitied Kingdom         China  127416.982143  
2             7.0   0.0  Unitied Kingdom       Bahrain   97022.421053  
3            11.0   0.0  Unitied Kingdom        Turkey   90781.068966  
4             8.0   1.0  Unitied Kingdom       Hungary   84341.085714  

[5 rows x 29 columns]

In [41]:
# get count of wins for driverId 1
df[df['driverId'] == 1]['wins'].sum()

920.0

In [42]:
# drop duplicates
df = df.drop_duplicates()

In [47]:
df.shape

(3755, 30)

In [43]:
# Import drivers_namescopy csv
drivers_names = pd.read_csv('../drivers_namescopy.csv')
df = df.merge(drivers_names, on='driverId', how='left')
df.head()


driverId       dob nationality dob_formatted  raceId  grid  \
0         1  1/7/1985     British          1985     2.0  12.0   
1         1  1/7/1985     British          1985     3.0   9.0   
2         1  1/7/1985     British          1985     4.0   5.0   
3         1  1/7/1985     British          1985     7.0  16.0   
4         1  1/7/1985     British          1985    10.0   4.0   

   results_position positionText  positionOrder  total_results_points  ...  \
0               7.0            7            7.0                   1.0  ...   
1               6.0            6            6.0                   3.0  ...   
2               4.0            4            4.0                   5.0  ...   
3              13.0           13           13.0                   0.0  ...   
4               1.0            1            1.0                  10.0  ...   

         date  dstnd_points  dstnd_position  wins   driver_country  \
0  2009-04-05           1.0            10.0   0.0  Unitied Kingdom   
1  2009-04-19           4.0            10.0   0.0  Unitied Kingdom   
2  2009-04-26           9.0             7.0   0.0  Unitied Kingdom   
3  2009-06-07           9.0            11.0   0.0  Unitied Kingdom   
4  2009-07-26          19.0             8.0   1.0  Unitied Kingdom   

   race_country   avg_lap_time forename   surname   combined_name  
0      Malaysia  109398.548387    Lewis  Hamilton  Lewis Hamilton  
1         China  127416.982143    Lewis  Hamilton  Lewis Hamilton  
2       Bahrain   97022.421053    Lewis  Hamilton  Lewis Hamilton  
3        Turkey   90781.068966    Lewis  Hamilton  Lewis Hamilton  
4       Hungary   84341.085714    Lewis  Hamilton  Lewis Hamilton  

[5 rows x 32 columns]

In [44]:
# drop forename and surname columns
df = df.drop(['forename', 'surname'], axis=1)

# Move combined_name column to the front of the df
cols = list(df.columns)
cols = [cols[-1]] + cols[:-1]
df = df[cols]
# Change combined_name to driver_name
df = df.rename(columns={
    'combined_name': 'driver_name',
})
df.head()


driver_name  driverId       dob nationality dob_formatted  raceId  grid  \
0  Lewis Hamilton         1  1/7/1985     British          1985     2.0  12.0   
1  Lewis Hamilton         1  1/7/1985     British          1985     3.0   9.0   
2  Lewis Hamilton         1  1/7/1985     British          1985     4.0   5.0   
3  Lewis Hamilton         1  1/7/1985     British          1985     7.0  16.0   
4  Lewis Hamilton         1  1/7/1985     British          1985    10.0   4.0   

   results_position positionText  positionOrder  ...  round  circuitId  \
0               7.0            7            7.0  ...    2.0        2.0   
1               6.0            6            6.0  ...    3.0       17.0   
2               4.0            4            4.0  ...    4.0        3.0   
3              13.0           13           13.0  ...    7.0        5.0   
4               1.0            1            1.0  ...   10.0       11.0   

             races_name        date  dstnd_points dstnd_position  wins  \
0  Malaysian Grand Prix  2009-04-05           1.0           10.0   0.0   
1    Chinese Grand Prix  2009-04-19           4.0           10.0   0.0   
2    Bahrain Grand Prix  2009-04-26           9.0            7.0   0.0   
3    Turkish Grand Prix  2009-06-07           9.0           11.0   0.0   
4  Hungarian Grand Prix  2009-07-26          19.0            8.0   1.0   

    driver_country race_country   avg_lap_time  
0  Unitied Kingdom     Malaysia  109398.548387  
1  Unitied Kingdom        China  127416.982143  
2  Unitied Kingdom      Bahrain   97022.421053  
3  Unitied Kingdom       Turkey   90781.068966  
4  Unitied Kingdom      Hungary   84341.085714  

[5 rows x 30 columns]

In [46]:
df.shape

(3755, 30)

In [49]:
# drop decimal place for year as a whole number
df['year'] = df['year'].astype(int)
df['year'].unique()

array([2009, 2008, 2007, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2020, 2021, 2022, 2006, 2005, 2004])

In [57]:
df['winner_name'] = df.loc[df.groupby(['year', 'races_name'])['results_position'].idxmin(), 'driver_name']

# replace NaN with N/A
df['winner_name'] = df['winner_name'].fillna('N/A')


df.head()

driver_name  driverId       dob nationality dob_formatted  raceId  grid  \
0  Lewis Hamilton         1  1/7/1985     British          1985     2.0  12.0   
1  Lewis Hamilton         1  1/7/1985     British          1985     3.0   9.0   
2  Lewis Hamilton         1  1/7/1985     British          1985     4.0   5.0   
3  Lewis Hamilton         1  1/7/1985     British          1985     7.0  16.0   
4  Lewis Hamilton         1  1/7/1985     British          1985    10.0   4.0   

   results_position positionText  positionOrder  ...  circuitId  \
0               7.0            7            7.0  ...        2.0   
1               6.0            6            6.0  ...       17.0   
2               4.0            4            4.0  ...        3.0   
3              13.0           13           13.0  ...        5.0   
4               1.0            1            1.0  ...       11.0   

             races_name        date  dstnd_points  dstnd_position wins  \
0  Malaysian Grand Prix  2009-04-05           1.0            10.0  0.0   
1    Chinese Grand Prix  2009-04-19           4.0            10.0  0.0   
2    Bahrain Grand Prix  2009-04-26           9.0             7.0  0.0   
3    Turkish Grand Prix  2009-06-07           9.0            11.0  0.0   
4  Hungarian Grand Prix  2009-07-26          19.0             8.0  1.0   

    driver_country  race_country   avg_lap_time     winner_name  
0  Unitied Kingdom      Malaysia  109398.548387             N/A  
1  Unitied Kingdom         China  127416.982143             N/A  
2  Unitied Kingdom       Bahrain   97022.421053             N/A  
3  Unitied Kingdom        Turkey   90781.068966             N/A  
4  Unitied Kingdom       Hungary   84341.085714  Lewis Hamilton  

[5 rows x 31 columns]

In [61]:
# Create a win ratio based on all races by year
df['win_ratio'] = df['wins'] / df['dstnd_position']
df.head()

driver_name  driverId       dob nationality dob_formatted  raceId  grid  \
0  Lewis Hamilton         1  1/7/1985     British          1985     2.0  12.0   
1  Lewis Hamilton         1  1/7/1985     British          1985     3.0   9.0   
2  Lewis Hamilton         1  1/7/1985     British          1985     4.0   5.0   
3  Lewis Hamilton         1  1/7/1985     British          1985     7.0  16.0   
4  Lewis Hamilton         1  1/7/1985     British          1985    10.0   4.0   

   results_position positionText  positionOrder  ...            races_name  \
0               7.0            7            7.0  ...  Malaysian Grand Prix   
1               6.0            6            6.0  ...    Chinese Grand Prix   
2               4.0            4            4.0  ...    Bahrain Grand Prix   
3              13.0           13           13.0  ...    Turkish Grand Prix   
4               1.0            1            1.0  ...  Hungarian Grand Prix   

         date  dstnd_points  dstnd_position  wins   driver_country  \
0  2009-04-05           1.0            10.0   0.0  Unitied Kingdom   
1  2009-04-19           4.0            10.0   0.0  Unitied Kingdom   
2  2009-04-26           9.0             7.0   0.0  Unitied Kingdom   
3  2009-06-07           9.0            11.0   0.0  Unitied Kingdom   
4  2009-07-26          19.0             8.0   1.0  Unitied Kingdom   

   race_country   avg_lap_time     winner_name  win_ratio  
0      Malaysia  109398.548387             N/A      0.000  
1         China  127416.982143             N/A      0.000  
2       Bahrain   97022.421053             N/A      0.000  
3        Turkey   90781.068966             N/A      0.000  
4       Hungary   84341.085714  Lewis Hamilton      0.125  

[5 rows x 32 columns]

In [64]:
df['driver_name'].unique()

array(['Lewis Hamilton', 'Nick Heidfeld', 'Nico Rosberg',
       'Fernando Alonso', 'Heikki Kovalainen', 'Kazuki Nakajima',
       'Sébastien Bourdais', 'Kimi Räikkönen', 'Robert Kubica',
       'Timo Glock', 'Takuma Sato', 'Nelson Piquet Jr.', 'Felipe Massa',
       'David Coulthard', 'Jarno Trulli', 'Adrian Sutil', 'Mark Webber',
       'Jenson Button', 'Anthony Davidson', 'Sebastian Vettel',
       'Giancarlo Fisichella', 'Rubens Barrichello', 'Ralf Schumacher',
       'Vitantonio Liuzzi', 'Alexander Wurz', 'Scott Speed',
       'Michael Schumacher', 'Juan Pablo Montoya', 'Christian Klien',
       'Tiago Monteiro', 'Jacques Villeneuve', 'Pedro de la Rosa',
       'Ricardo Zonta', 'Antônio Pizzonia', 'Olivier Panis', 'Marc Gené',
       'Sébastien Buemi', 'Luca Badoer', 'Jaime Alguersuari',
       'Romain Grosjean', 'Kamui Kobayashi', 'Nico Hülkenberg',
       'Vitaly Petrov', 'Bruno Senna', 'Pastor Maldonado',
       'Paul di Resta', 'Sergio Pérez', "Jérôme d'Ambrosio",
       'Dani

In [62]:
df.columns

Index(['driver_name', 'driverId', 'dob', 'nationality', 'dob_formatted',
       'raceId', 'grid', 'results_position', 'positionText', 'positionOrder',
       'total_results_points', 'results_laps', 'fastestLap', 'rank',
       'race_time', 'results_fastestlaptime', 'fastestLapSpeed', 'statusId',
       'status', 'year', 'round', 'circuitId', 'races_name', 'date',
       'dstnd_points', 'dstnd_position', 'wins', 'driver_country',
       'race_country', 'avg_lap_time', 'winner_name', 'win_ratio'],
      dtype='object')

In [63]:
# # save to csv
df.to_csv('../VisualizationDF.csv', index=False)